# Generated by Django 5.1.3 on 2024-11-15 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_donation_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='adminremark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='collectionloc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationatea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.donationarea'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(blank=True, choices=[('Food Donation', 'Food Donation'), ('Cloth Donation', 'Cloth Donation'), ('Footwear Donation', 'Footwear Donation'), ('Books Donation', 'Books Donation'), ('Furniture Donation', 'Furniture Donation'), ('Vessel Donation', 'Vessel Donation'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='updationdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='volunteerremark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
